name: Django CI/CD

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 프론트 서버 배포
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      set -e
                      cd /home/ubuntu/app/movie-cookie-fe
                      git pull origin main
